"use server";

import OpenAI from "openai";

const client = new OpenAI({
  apiKey: process.env.NEXT_PUBLIC_OPENROUTER_API_KEY,
  baseURL: "https://openrouter.ai/api/v1",
  defaultHeaders: {
    "HTTP-Referer": "https://your-site-url.com",
    "X-Title": "JobWin AI"
  }
});

export async function generateCoverLetter(prevState, formData) {
  const userName = formData.get("name");
  const jobTitle = formData.get("jobTitle");
  const companyName = formData.get("companyName");
  const userSkills = formData.get("skills");
  const email = formData.get("email");
  const phoneNumber = formData.get("phoneNumber");
  const linkedin = formData.get("linkedin");
  const github = formData.get("github");
  const portfolio = formData.get("portfolio");

  const date = new Date().toLocaleDateString("en-US", {
    month: "long",
    day: "numeric",
    year: "numeric"
  });

  const prompt = `
You are a professional cover letter writer.

Write a COMPLETE, READY-TO-SEND cover letter using the exact format below.
Do NOT include explanations, markdown, headings, or placeholders.
Do NOT mention that this was generated by AI.
Omit any optional contact fields if not provided.

FORMAT EXACTLY LIKE THIS:

${date}
Hiring Manager
${companyName}

Dear Hiring Manager,

[Opening paragraph: introduce ${userName}, mention applying for ${jobTitle} at ${companyName}, express enthusiasm.]

[Second paragraph: highlight 2–3 relevant skills from ${userSkills} with impact and confidence.]

[Third paragraph: explain interest in ${companyName}, cultural fit, and readiness to contribute.]

[Closing paragraph: thank the employer, express eagerness for an interview.]

Sincerely,
${userName}
${email}
${phoneNumber}
${linkedin ? linkedin : ""} 
${github ? github : ""} 
${portfolio ? portfolio : ""} 

Keep the tone professional, confident, and polite.
Limit to 250–300 words.
`;

  try {
    const response = await client.chat.completions.create({
      model: "meta-llama/llama-3.3-70b-instruct:free",
      messages: [{ role: "user", content: prompt }],
      temperature: 0.6
    });

    return {
      success: true,
      coverLetter: response.choices[0].message.content.trim()
    };
  } catch (error) {
    console.error("Error generating cover letter:", error);
    return {
      success: false,
      coverLetter: "Error generating cover letter."
    };
  }
}
